[package]
name = "start_project"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
tui = "0.19"
reqwest = "0.12.4"
tokio = { version = "1", features = ["full"] }
tui-input = "0.8.0"
tui-scrollview = "0.3.6"
